### ISSUE TITLE
some questions about ./autogen

### ISSUE THREAD

**Issue by legend-issue** [aflgo/aflgo#10]
clang-6.0: error: unsupported option '-V -g'
configure:3582: $? = 1
configure:3571: /home/aflgo/aflgo/afl-clang-fast -qversion >&5
clang-6.0: error: unknown argument: '-qversion'
configure:3582: $? = 1
configure:3602: checking whether the C compiler works
configure:3624: /home/aflgo/aflgo/afl-clang-fast  -targets=/home/aflgo/temp/BBtargets.txt -outdir=/home/aflgo/temp -flto -fuse-ld=gold -Wl,-plugin-opt=save-temps  -L/usr/lib conftest.c -lpthreads >&5
/usr/bin/ld.gold: error: cannot find -lpthreads

but when I use root permission,it could be done,but the Ftargets.txt is empty,I want to know the reason of these problems

**Comment by thuanpv** [comment]
Hi,
Can you share with us the project you are working on and your setup (e.g., OS version, GCC version)? I see 3 errors here but without the project source it is difficult to reproduce the problems and find the root cause. 
Thuan

**Comment by yyyyxf** [comment]
use -lpthread instead of -lpthreads

**Comment by legend-issue** [comment]
Thank you ,I have resolve this :)

2017-11-16 16:37 GMT+08:00 yyyyxf <notifications@github.com>:
