### ISSUE TITLE
cd: /aflgo: No such file or directory when sudo ./aflgo-build.sh

### ISSUE THREAD

**Issue by Ricardio609** [aflgo/aflgo#107]
https://github.com/aflgo/aflgo/blob/52496972bb23eec62c6586c88d90801f6add494d/scripts/build/aflgo-build.sh#L71
./aflgo-build.sh: line 71: cd: /aflgo: No such file or directory

I should create the folder manually？

**Comment by strongcourage** [comment]
thanks @Ricardio609, I fixed it.
