### ISSUE TITLE
How do I debug AFLgo if I want to make improvements based on it?

### ISSUE THREAD

**Issue by laobameishijia** [aflgo/aflgo#114]

**Comment by mboehme** [comment]
Unfortunately, there is no easy way to debug a fuzzer. If you want to debug afl-fuzz, you could run it with the environment variable AFL_NO_UI set and use OKF or WARNF for logging.

**Comment by laobameishijia** [comment]
Thanks for your reply, What needs to be added is that "set follow-fork-mode parent" needs to be added in launch.json file when vscode's GBD debugging plug-in is used.

**Comment by mboehme** [comment]
Thanks for following up!
