### ISSUE TITLE
Can't test on aflgo on libxml2

### ISSUE THREAD

**Issue by Ljfanny** [aflgo/aflgo#118]
I followed the step 7 in README.md to build libxml2, but it failed when I execute ./autogen.
The error messages is as follows:
```
checking for zlib.h... yes
checking for gzread in -lz... yes
Checking lzma
./configure: line 13122: syntax error near unexpected token `LZMA,liblzma,'
./configure: line 13122: `    PKG_CHECK_MODULES(LZMA,liblzma,'

Now type 'make' to compile libxml2.
```

**Comment by mboehme** [comment]
can you try: `sudo apt-get install -y lzma`? Let us know how it goes.

**Comment by Ljfanny** [comment]
> If you are on Ubuntu, can you try: `sudo apt-get install -y lzma`? Let us know how it goes.

I‘ve already installed lzma before I execute ./autogen

```
lzma is already the newest version (9.22-2ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by mboehme** [comment]
Have you installed autoconf, automake, and pkg-config?

**Comment by Ljfanny** [comment]
> Have you installed autoconf, automake, and pkg-config?

It works after installing pkg-config. Thanks!
