### ISSUE TITLE
Build sqlite by afl-clang-fast

### ISSUE THREAD

**Issue by stlmx** [aflgo/aflgo#127]
Great works !

I am new to FUZZ, my teacher ask me to build sqlite by afl-clang-fast and I follow the steps by README.md of AFLGO
However, I meet the problem as follows:

*******
/usr/bin/ld: bad -plugin-opt option                                                                                                                                                             

clang-11: error: linker command failed with exit code 1 (use -v to see invocation)  
*******

I can build sqlite by afl-gcc, gcc, clang and afl-clang.
Please save me ! ! wuwuuwuwuwuuwu !

**Comment by mboehme** [comment]
Can you check of clang was build with the Gold plugin? You could also try using our dockerfile which has the Gold plugin installed.
