### ISSUE TITLE
Cannot observe the crash in simple C program

### ISSUE THREAD

**Issue by hcantunc** [aflgo/aflgo#128]
Hi, I am trying to use aflgo on the following simple program. I followed the steps described [here](https://github.com/aflgo/aflgo/blob/master/Readme.md) and I set the target as line 13 (i.e., the statement `val = 1;`). The following distance values are obtained after instrumentation: `test.c:13,1.0 test.c:6,2.0`. I am able to run the fuzzer, however, I am not able to observe the crash in this program. The abort statement is never reached even when the initial seed should be able to reach it. I am using LLVM version 11. Is there something that I am missing?

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>


int main(int argc, char** argv) {
  char buf[8];
  read(0, buf, 8);

  int val = 0;

  if (buf[0] == '2') {
    val = 1;
  }

  if (val == 1) {
    abort();
  }

  return 0;
}
```

**Comment by mboehme** [comment]
This is likely due to the abort statement not leading to a signal that is recognized as a crash by AFL.

Not tested, but you could manually raise a SIGSEGV: `raise(SIGSEGV)`
