### ISSUE TITLE
How to direct to code in a shared library

### ISSUE THREAD

**Issue by shijy16** [aflgo/aflgo#133]
Hi, I am new to aflgo. And I want to fuzz a binary which loads a shared library(.so) and direct the fuzzing process to a line in the shared library.

The shared library and the main binary are compiled seperately. How can I merge the distance files of them and run aflgo as I expect?

**Comment by mboehme** [comment]
If you can instrument the shared library with AFLGo, it should be possible to direct the search to a target within the shared library. In the "host", you can set the calls to the shared library as your targets.

Closing as not a bug, but feel free to continue asking questions.
