### ISSUE TITLE
gen_distance_fast.py: error: Couldn't find any binaries in folder /home/chen/aflgo/libxml2.

### ISSUE THREAD

**Issue by DehaoMeng** [aflgo/aflgo#145]
When I run `$AFLGO/distance/gen_distance_fast.py $SUBJECT $TMP_DIR xmllint` I get a gen_distance_fast.py: error: Couldn't find any binaries in folder /home/chen/aflgo/libxml2.  I've gone through the above steps but when I run ls 
```
$TMP_DIR/dot-files
echo "Function targets"
cat $TMP_DIR/Ftargets.tx
# Clean up
cat $TMP_DIR/BBnames.txt | grep -v "^$"| rev | cut -d:  -f2- | rev | sort | uniq > $TMP_DIR/BBnames2.txt && mv $TMP_DIR/BBnames2.txt $TMP_DIR/BBnames.txt

cat $TMP_DIR/BBcalls.txt | grep -Ev "^[^,]*$|^([^,]*,){2,}[^,]*$"| sort | uniq > $TMP_DIR/BBcalls2.txt && mv  $TMP_DIR/BBcalls2.txt $TMP_DIR/BBcalls.txt
```
There will be No such file or directory error is not here to the following impact

**Comment by SonicStark** [comment]
I am not sure I fully understand what you write. You need to check if `libxml` is properly built with `aflgo-clang`, mentioned in step 6 - [readme](https://github.com/aflgo/aflgo#how-to-instrument-a-binary-with-aflgo).
