### ISSUE TITLE
cannot build 

### ISSUE THREAD

**Issue by z1w** [aflgo/aflgo#22]
At step 7, I was trying to build libxml2. When running "./configure --disable-shared", I received the error message:
"checking for gcc... $LOCAL_PATH/aflgo/aflgo/afl-clang-fast
checking whether the C compiler works... no
configure: error: in `$LOCAL_PATH/aflgo/libxml2':
configure: error: C compiler cannot create executables"

My LLVM version is LLVM5.0.0

**Comment by thuanpv** [comment]
Can you try with LLVM 4.0 or LLVM 3.8?
