### ISSUE TITLE
error when test on diffutils

### ISSUE THREAD

**Issue by z1w** [aflgo/aflgo#28]
Hi,

I use LLVM4.0 and work on diffutils using AFLGO. I received this error message:

aflgo-llvm-pass (yeah!) 2.49b (preprocessing mode)
#0 0x00007f7e4beefba8 llvm::sys::PrintStackTrace(llvm::raw_ostream&) MY_LOCAL_PATH/llvm_4.0/src/lib/Support/Unix/Signals.inc:406:0
#1 0x00007f7e4beedd2e llvm::sys::RunSignalHandlers() MY_LOCAL_PATH/llvm_4.0/src/lib/Support/Signals.cpp:45:0
#2 0x00007f7e4beede7c SignalHandler(int) MY_LOCAL_PATH/llvm_4.0/src/lib/Support/Unix/Signals.inc:246:0
#3 0x00007f7e4ae294b0 (/lib/x86_64-linux-gnu/libc.so.6+0x354b0)
#4 0x00007f7e4af42168 /build/glibc-Cl5G7W/glibc-2.23/string/../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:245:0
#5 0x00007f7e4bed4be1 memcpy /usr/include/x86_64-linux-gnu/bits/string3.h:53:0
#6 0x00007f7e4bed4be1 void llvm::SmallVectorTemplateBase<char, true>::uninitialized_copy<char const, char>(char const*, char const*, char*, std::enable_if<std::is_same<std::remove_const<char const>::type, char>::value, void>::type*) MY_LOCAL_PATH/llvm_4.0/src/include/llvm/ADT/SmallVector.h:296:0
#7 0x00007f7e4bed4be1 void llvm::SmallVectorImpl<char>::append<char const*>(char const*, char const*) MY_LOCAL_PATH/llvm_4.0/src/include/llvm/ADT/SmallVector.h:399:0
#8 0x00007f7e4bed4be1 llvm::raw_svector_ostream::write_impl(char const*, unsigned long) MY_LOCAL_PATH/llvm_4.0/src/lib/Support/raw_ostream.cpp:741:0
#9 0x00007f7e4bed5787 llvm::raw_ostream::write(char const*, unsigned long) MY_LOCAL_PATH/llvm_4.0/src/lib/Support/raw_ostream.cpp:225:0
#10 0x00007f7e4bec3f68 llvm::Twine::print(llvm::raw_ostream&) const MY_LOCAL_PATH/llvm_4.0/src/lib/Support/Twine.cpp:165:0
#11 0x00007f7e4bec4189 llvm::raw_pwrite_stream::~raw_pwrite_stream() MY_LOCAL_PATH/llvm_4.0/src/include/llvm/Support/raw_ostream.h:333:0
#12 0x00007f7e4bec4189 llvm::raw_svector_ostream::~raw_svector_ostream() MY_LOCAL_PATH/llvm_4.0/src/include/llvm/Support/raw_ostream.h:510:0
#13 0x00007f7e4bec4189 llvm::Twine::toVector(llvm::SmallVectorImpl<char>&) const MY_LOCAL_PATH/llvm_4.0/src/lib/Support/Twine.cpp:33:0
#14 0x00007f7e4bec422d llvm::SmallVectorTemplateCommon<char, void>::begin() const MY_LOCAL_PATH/llvm_4.0/src/include/llvm/ADT/SmallVector.h:117:0
#15 0x00007f7e4bec422d llvm::SmallVectorTemplateCommon<char, void>::size() const MY_LOCAL_PATH/llvm_4.0/src/include/llvm/ADT/SmallVector.h:135:0
#16 0x00007f7e4bec422d llvm::Twine::toStringRef(llvm::SmallVectorImpl<char>&) const MY_LOCAL_PATH/llvm_4.0/src/include/llvm/ADT/Twine.h:467:0
#17 0x00007f7e4bec422d llvm::Twine::str[abi:cxx11]() const MY_LOCAL_PATH/llvm_4.0/src/lib/Support/Twine.cpp:29:0
#18 0x00007f7e4a0842a3 llvm::DOTGraphTraits<llvm::Function const*>::getEdgeAttributes[abi:cxx11](llvm::BasicBlock const*, llvm::TerminatorInst::SuccIterator<llvm::TerminatorInst const*, llvm::BasicBlock const>, llvm::Function const*) MY_LOCAL_PATH/llvm_4.0/install/include/llvm/Analysis/CFGPrinter.h:0:18
#19 0x00007f7e4a083960 llvm::GraphWriter<llvm::Function const*>::writeEdge(llvm::BasicBlock const*, unsigned int, llvm::TerminatorInst::SuccIterator<llvm::TerminatorInst const*, llvm::BasicBlock const>) MY_LOCAL_PATH/llvm_4.0/install/include/llvm/Support/GraphWriter.h:244:7
#20 0x00007f7e4a083652 llvm::GraphWriter<llvm::Function const*>::writeNode(llvm::BasicBlock const*) MY_LOCAL_PATH/llvm_4.0/install/include/llvm/Support/GraphWriter.h:221:5
#21 0x00007f7e4a081ce3 llvm::ilist_node_base<false>::getNext() const MY_LOCAL_PATH/llvm_4.0/install/include/llvm/ADT/ilist_node_base.h:30:45
#22 0x00007f7e4a081ce3 llvm::ilist_node_impl<llvm::ilist_detail::node_options<llvm::BasicBlock, false, false, void> >::getNext() const MY_LOCAL_PATH/llvm_4.0/install/include/llvm/ADT/ilist_node.h:74:0
#23 0x00007f7e4a081ce3 llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::BasicBlock, false, false, void>, false, true>::operator++() MY_LOCAL_PATH/llvm_4.0/install/include/llvm/ADT/ilist_iterator.h:158:0
#24 0x00007f7e4a081ce3 llvm::simple_ilist<llvm::BasicBlock>::begin() const MY_LOCAL_PATH/llvm_4.0/install/include/llvm/ADT/simple_ilist.h:114:0
#25 0x00007f7e4a081ce3 llvm::Function::begin() const MY_LOCAL_PATH/llvm_4.0/install/include/llvm/IR/Function.h:536:0
#26 0x00007f7e4a081ce3 llvm::GraphTraits<llvm::Function const*>::nodes_begin(llvm::Function const*) MY_LOCAL_PATH/llvm_4.0/install/include/llvm/IR/CFG.h:234:0
#27 0x00007f7e4a081ce3 llvm::GraphWriter<llvm::Function const*>::writeNodes() MY_LOCAL_PATH/llvm_4.0/install/include/llvm/Support/GraphWriter.h:146:0
#28 0x00007f7e4a081ce3 llvm::GraphWriter<llvm::Function const*>::writeGraph(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) MY_LOCAL_PATH/llvm_4.0/install/include/llvm/Support/GraphWriter.h:109:0
#29 0x00007f7e4a081ce3 llvm::raw_ostream& llvm::WriteGraph<llvm::Function const*>(llvm::raw_ostream&, llvm::Function const* const&, bool, llvm::Twine const&) MY_LOCAL_PATH/llvm_4.0/install/include/llvm/Support/GraphWriter.h:307:0
#30 0x00007f7e4a081ce3 (anonymous namespace)::AFLCoverage::runOnModule(llvm::Module&) MY_LOCAL_PATH/aflgo/aflgo/llvm_mode/afl-llvm-pass.so.cc:396:0
#31 0x00007f7e4bfb9e4f runOnModule MY_LOCAL_PATH/llvm_4.0/src/lib/IR/LegacyPassManager.cpp:1590:0
#32 0x00007f7e4bfb9e4f llvm::legacy::PassManagerImpl::run(llvm::Module&) MY_LOCAL_PATH/llvm_4.0/src/lib/IR/LegacyPassManager.cpp:1693:0
#33 0x00000000007920f5 llvm::PrettyStackTraceString::~PrettyStackTraceString() MY_LOCAL_PATH/llvm_4.0/src/include/llvm/Support/PrettyStackTrace.h:52:0
#34 0x00000000007920f5 EmitAssembly MY_LOCAL_PATH/llvm_4.0/src/tools/clang/lib/CodeGen/BackendUtil.cpp:723:0
#35 0x00000000007920f5 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) MY_LOCAL_PATH/llvm_4.0/src/tools/clang/lib/CodeGen/BackendUtil.cpp:978:0
#36 0x0000000000b2e1a7 std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >::~unique_ptr() /usr/include/c++/5/bits/unique_ptr.h:235:0
#37 0x0000000000b2e1a7 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) MY_LOCAL_PATH/llvm_4.0/src/tools/clang/lib/CodeGen/CodeGenAction.cpp:229:0
#38 0x0000000000c4bb58 void std::swap<bool>(bool&, bool&) /usr/include/c++/5/bits/move.h:187:0
#39 0x0000000000c4bb58 clang::ParseAST(clang::Sema&, bool, bool) MY_LOCAL_PATH/llvm_4.0/src/tools/clang/lib/Parse/ParseAST.cpp:161:0
#40 0x0000000000aa9e2e clang::FrontendAction::Execute() MY_LOCAL_PATH/llvm_4.0/src/tools/clang/lib/Frontend/FrontendAction.cpp:459:0
#41 0x0000000000a7a616 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) MY_LOCAL_PATH/llvm_4.0/src/tools/clang/lib/Frontend/CompilerInstance.cpp:954:0
#42 0x0000000000b28a62 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) MY_LOCAL_PATH/llvm_4.0/src/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:249:0
#43 0x0000000000752c48 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) MY_LOCAL_PATH/llvm_4.0/src/tools/clang/tools/driver/cc1_main.cpp:221:0
#44 0x000000000074f25e ExecuteCC1Tool MY_LOCAL_PATH/llvm_4.0/src/tools/clang/tools/driver/driver.cpp:299:0
#45 0x000000000074f25e main MY_LOCAL_PATH/llvm_4.0/src/tools/clang/tools/driver/driver.cpp:380:0
#46 0x00007f7e4ae14830 __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:325:0
#47 0x0000000000751029 _start (MY_LOCAL_PATH/llvm_4.0/install/bin/clang-4.0+0x751029)
Stack dump:
0.	Program arguments: MY_LOCAL_PATH/llvm_4.0/install/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm-bc -flto -disable-free -disable-llvm-verifier -discard-value-names -main-file-name regex.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -coverage-notes-file MY_LOCAL_PATH/aflgo/diffutils/lib/regex.gcno -resource-dir MY_LOCAL_PATH/llvm_4.0/install/bin/../lib/clang/4.0.0 -dependency-file .deps/regex.Tpo -sys-header-deps -MP -MT regex.o -I . -D __AFL_HAVE_MANUAL_CONTROL=1 -D __AFL_COMPILER=1 -D FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1 -D __AFL_LOOP(_A)=({ static volatile char *_B __attribute__((used));  _B = (char*)"##SIG_AFL_PERSISTENT##"; __attribute__((visibility("default"))) int _L(unsigned int) __asm__("__afl_persistent_loop"); _L(_A); }) -D __AFL_INIT()=do { static volatile char *_A __attribute__((used));  _A = (char*)"##SIG_AFL_DEFER_FORKSRV##"; __attribute__((visibility("default"))) void _I(void) __asm__("__afl_manual_init"); _I(); } while (0) -internal-isystem /usr/local/include -internal-isystem MY_LOCAL_PATH/llvm_4.0/install/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -fdebug-compilation-dir MY_LOCAL_PATH/aflgo/diffutils/lib -ferror-limit 19 -fmessage-length 184 -funroll-loops -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -load MY_LOCAL_PATH/aflgo/aflgo/afl-llvm-pass.so -mllvm -targets=MY_LOCAL_PATH/aflgo/diffutils//BBtargets.txt -mllvm -outdir=MY_LOCAL_PATH/aflgo/diffutils/ -o regex.o -x c regex.c 
1.	<eof> parser at end of file
2.	Per-module optimization passes
3.	Running pass 'Unnamed pass: implement Pass::getPassName()' on module 'regex.c'.
clang-4.0: error: unable to execute command: Segmentation fault (core dumped)
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /u/z/w/zw/llvm_4.0/install/bin

How could I fix this problem?

**Comment by mboehme** [comment]
We are aware of this problem and are currently working on a solution.

This is the problematic line:
```
#30 0x00007f7e4a081ce3 (anonymous namespace)::AFLCoverage::runOnModule(llvm::Module&) MY_LOCAL_PATH/aflgo/aflgo/llvm_mode/afl-llvm-pass.so.cc:396:0
```

The LLVM GraphWriter crashes in some (deterministic) cases when AFLGo asks it to print a function's CFG into a dot-file.

Closing as duplicate of #25 .
