### ISSUE TITLE
Tutorial changes

### ISSUE THREAD

**Issue by jeffball55** [aflgo/aflgo#3]
In order to successfully follow along in the tutorial guide (for libxml2), I needed to run `export LDFLAGS=-lpthreads` before the configure line, otherwise xmllint would fail to run because of a missing `pthreads_getspecific` symbol (along with others probably).

Additionally, the configure script specifies the disable shared flag should be `--disable-shared` instead of `-disable-shared` (two dashes instead of one).

Could you please update the tutorial, so that others can more easily follow along?

**Comment by jeffball55** [comment]
Additionally, I needed to install `pydot` (in addition to `pydotplus`):
```
sudo pip3 install pydot
```

**Comment by aflgo** [comment]
Done. Thanks for pointing this out.
