### ISSUE TITLE
Distance Calculation

### ISSUE THREAD

**Issue by valour01** [aflgo/aflgo#31]
Hi. According to the tutorial. I found that target information is used while building the binary and generating the distance.

It seems that we have to build the binary once again with the generated distance. Actually, I want to know when the target information is used during the whole work flow. 

In other words, if I changed my targets. What information could be used and what are need to be generated once again? Is the distance information related to the targets or it is the information for the whole binary and could be reused no matter how we change the targets. Many Thanks

**Comment by mboehme** [comment]
The target information is used in the first step to determine the corresponding target basic blocks and target functions in the LLVM-IR. The dot-files are generated. The distance values are computed. A second LLVM-pass instruments the program. Of course, with some more work this could all be done in a single LLVM-pass. Volunteers welcome :)
