### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by valour01** [aflgo/aflgo#32]
I want to fuzz binaries in ARM architecture. Do aflgo support all of the feature in qemu mode. If not, what things can I do to make aflgo support arm.

**Comment by thuanpv** [comment]
Hi,
Currently, AFLGo does not support qemu mode. 

One of the core parts of AFLGo is its instrumentation to calculate the distance to target(s) in run-time. If you can support the extra instrumentation, it should work.

You may want to consider using DynamoRIO to support ARM as well. As claimed by the tool, DynamoRIO supports ARM and DynamoRIO has been used in WinAFL to do dynamic binary instrumentation. You can take a look at WinAFL code.

Hope it helps.

Thuan
