### ISSUE TITLE
cannot generate Ftargets

### ISSUE THREAD

**Issue by z1w** [aflgo/aflgo#34]
I was running AFLGO on a test program. I specified one of the lines with some code as BBtarget, but the result Ftargets.txt was empty. 

In AFLGO's llvm pass file(afl-llvm-pass.so.cc), I modified the code to let each instruction write its line number to a disk file but inside the disk file I cannot find my target line number...This situation is very confused to me...

I wrote a llvm pass before and my pass can output the my target line number. The difference is that my tool uses llvm-5.0, while AFLGO uses llvm-4.0. I do not know whether the problem is caused by different versions of llvm.

**Comment by yxliang01** [comment]
FYI, there are many people failed to use AFLGO with llvm-5.0, before more experienced people commenting to this post, I would suggest you trying llvm-4.0 if you tool can support it.

**Comment by z1w** [comment]
I used llvm-4.0 when I work with AFLGO. I use llvm-5.0 for my own tool. In both tools (my tool and AFLGO), I did a very simple thing: for each instruction, output the line number to a file. However, in AFLGO, that file does not have the line I want to reach.

**Comment by z1w** [comment]
Some updates: I changed my tool and used llvm-4.0 for my tool. The file with all line numbers contains the target line...

**Comment by mboehme** [comment]
Great suggestion! Closing as fixed (in commit d98ad65).
