### ISSUE TITLE
potential discrepancy in calculating the distance

### ISSUE THREAD

**Issue by z1w** [aflgo/aflgo#41]
Hi,

I tried to instrument the libxml2 project. While I compile the project on two different machines (they share the same file system, the major difference is that they have different processors), the distance results computed are different. The result in distance.cfg computed on one machine is a strict subset of the other one.

What I found is that the input files to the genDistance.sh script on two machines are already different, for example, the BBname files. However, if I did not compile libxml2 in parallel, the result on both machines are the same. Operationally, if I changed " make -j$(nproc) all" to "make all", the issue would be resolved. The files generated on two machines are the same. So I am wondering whether parallelizing the compilation might lead to inaccuracy when computing the distance.

**Comment by mboehme** [comment]
Interesting observation! Updated the tutorial.
