### ISSUE TITLE
distance.callgraph.txt: No such file or directory

### ISSUE THREAD

**Issue by CCWANG19** [aflgo/aflgo#42]
Hi,
when I use aflgo, i always meet a problem that the cat: ..../AFLGO/temp/distance.callgraph.txt: No such file or directory
there are my environment
subject:libxml2
OS: ubuntu 16.04
LLVM: 4.0

and when i excute the command $AFLGO/scripts/genDistance.sh $SUBJECT $TMP_DIR xmllint, the result is 
(1) Constructing CG for /home/wcc/Downloads/AFLGO/libxml2/.libs/xmllint..
(2) Computing distance for call graph ..
cat: /home/wcc/Downloads/AFLGO/temp/distance.callgraph.txt: No such file or directory

Parsing /home/wcc/Downloads/AFLGO/temp/dot-files/callgraph.dot ..
Name: Call graph
Type: DiGraph
Number of nodes: 252
Number of edges: 765
Average in degree:   3.0357
Average out degree:   3.0357

Working in CG mode..
Loading targets..
No targets available
-- Problem in Step 2 of generating !
-- You can resume by executing:
$ /home/wcc/Downloads/AFLGO/aflgo/scripts/genDistance.sh /home/wcc/Downloads/AFLGO/libxml2 /home/wcc/Downloads/AFLGO/temp xmllint /home/wcc/Downloads/AFLGO/temp

And the Ftargets.txt is 
xmlAddID__internal_alias
xmlAddID
step2.log is
Parsing /home/wcc/Downloads/AFLGO/temp/dot-files/callgraph.dot ..
Name: Call graph
Type: DiGraph
Number of nodes: 252
Number of edges: 765
Average in degree:   3.0357
Average out degree:   3.0357

Working in CG mode..
Loading targets..
No targets available

Thanks!

**Comment by thuanpv** [comment]
Hi,

What are your target statements? Can you please upload your BBtargets.txt file?

Best regards,

Thuan

**Comment by CCWANG19** [comment]
Thank you for your reply!
And my BBtargets.txt is
valid.c:2637
valid.c:2638
valid.c:2639
valid.c:2640

And I use 
git checkout ef709ce2
git diff -U0 HEAD^ HEAD > $TMP_DIR/commit.diff
cat $TMP_DIR/commit.diff |  $TMP_DIR/showlinenum.awk show_header=0 path=1 | grep -e "\.[ch]:[0-9]*:+" -e "\.cpp:[0-9]*:+" -e "\.cc:[0-9]*:+" | cut -d+ -f1 | rev | cut -c2- | rev > $TMP_DIR/BBtargets.txt
this  commond to git the BBtargets.txt file.
thank you!

**Comment by thuanpv** [comment]
I figure out that the issue normally happens if LLVMgold is not installed properly. Please try to follow the installation steps in the attached file to see whether the issue is resolved. It helps some guys to resolve similar issues.
[Installation_clang_4.docx](https://github.com/aflgo/aflgo/files/3250304/Installation_clang_4.docx)

**Comment by zjuchenyuan** [comment]
@thuanpv I meet same issue, and I am sure that I followed just like your installation steps.

I have same questions like #48 , why do you extract `$LLVM_REVISION` from `chromium_tools` but do not use it? And why do you remove MSAN related steps?

I will build a Docker image soon.

**Comment by thuanpv** [comment]
Hi @zjuchenyuan,

I have updated the aflgo-build.sh script. Please let me know if the issue is gone.

Thanks,

Thuan

**Comment by strongcourage** [comment]
@zjuchenyuan: We used the oss-fuzz's script to install clang and LLVMgold plugin and AFLGo worked as expected. You can keep MSAN if you need it.

@CCWANG19: I would recommend you to use this [script](../tree/master/scripts/build/aflgo-build.sh) to install AFLGo and then use this [script](../tree/master/scripts/fuzz/libxml2-ef709ce2.sh) to fuzz libxml2. Thanks.

**Comment by peach-byte** [comment]
Hi
I have the same problem :
```
$AFLGO/scripts/genDistance.sh $SUBJECT $TMP_DIR gdimagecolormatch
```
```
(2) Computing distance for call graph ..
cat: /home/ubuntu16/Documents/github-repos/libgd/obj-aflgo/temp/distance.callgraph.txt: No such file or directory

Parsing /home/ubuntu16/Documents/github-repos/libgd/obj-aflgo/temp/dot-files/callgraph.dot ..
Traceback (most recent call last):
  File "/home/ubuntu16/aflgo/scripts/distance.py", line 109, in <module>
    G = nx.DiGraph(nx.drawing.nx_pydot.read_dot(args.dot))
  File "<decorator-gen-714>", line 2, in read_dot
  File "/usr/local/lib/python3.5/dist-packages/networkx/utils/decorators.py", line 214, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu16/Documents/github-repos/libgd/obj-aflgo/temp/dot-files/callgraph.dot'
-- Problem in Step 2 of generating !
-- You can resume by executing:
$ /home/ubuntu16/aflgo/scripts/genDistance.sh /home/ubuntu16/Documents/github-repos/libgd /home/ubuntu16/Documents/github-repos/libgd/obj-aflgo/temp gdimagecolormatch /home/ubuntu16/Documents/github-repos/libgd/obj-aflgo/temp
```

I have a lot of dot file for callgrah in my dot-file folder but all have a suffix for example : 
callgraph.bug00248a.dot

**Comment by strongcourage** [comment]
Hi @peach-byte,
I try the latest version 2.2.5 of libgd. Given your target `gd_color_match.c:35`, the file Ftargets.txt is empty. Thus, I change this file a bit, now the BBtargets.txt contains `gd_color_match.c:37` (maybe you used another version and did not have this issue). 

The generated Ftargets.txt contains the function `gdImageColorMatch` as expected, however I have the same issue as yours since the callgraph in dot does not have the node `gdImageColorMatch`, consequently AFLGo could not generate the file `distance.callgraph.txt`.

You should probably try different targets. Best.

**Comment by peach-byte** [comment]
Tank you for reply.
although my Ftargets.txt is not empty I don't have callgraph dot file at all.
my head is this commit:
2e886046f86d0d6bfc14aab94a881259a081e3f4

> Hi @peach-byte,
> I try the latest version 2.2.5 of libgd. Given your target `gd_color_match.c:35`, the file Ftargets.txt is empty. Thus, I change this file a bit, now the BBtargets.txt contains `gd_color_match.c:37` (maybe you used another version and did not have this issue).
> 
> The generated Ftargets.txt contains the function `gdImageColorMatch` as expected, however I have the same issue as yours since the callgraph in dot does not have the node `gdImageColorMatch`, consequently AFLGo could not generate the file `distance.callgraph.txt`.
> 
> You should probably try different targets. Best.

**Comment by strongcourage** [comment]
I used your version, run `make check`, then I used a different commands  as follows:
~~~
cd tests/gdimagecolormatch
$AFLGO/scripts/genDistance.sh $SUBJECT $TMP_DIR gdimagecolormatch
~~~
So given BBtargets.txt `gd_color_match.c:36`, I can generate `distance.callgraph.txt` but `distance.cfg.txt` is empty :). You can find the folder [temp.zip](https://github.com/aflgo/aflgo/files/4754857/temp.zip).

To fuzz gdimagecolormatch, you still need to choose appropriate targets. Best.

**Comment by peach-byte** [comment]
> cd tests/gdimagecolormatch
> $AFLGO/scripts/genDistance.sh $SUBJECT $TMP_DIR gdimagecolormatch

why `distance.cfg.txt` is empty?
I review step2.log file but no useful information.
