### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Fayozbek** [aflgo/aflgo#43]
Hi, first of all, thank you for the awesome tool. During the installation of LLVM and Gold plugin (https://github.com/aflgo/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh#L28) 
When I run `cmake -G "Ninja" \
      -DLIBCXX_ENABLE_SHARED=OFF -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
      -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86" \
      -DLLVM_BINUTILS_INCDIR=/usr/include $SRC/llvm`
 I have an error:
CMake Error: The source directory "/llvm" does not appear to contain CMakeLists.txt.
Any advice will be appreciated, thank you!

**Comment by thuanpv** [comment]
Hi. Thanks for your interest in our work. Please try to follow the installation steps in the attached file to install Clang/LLVM 4.0 and LLVM-Gold. It could resolve the issue.
[Installation_clang_4.docx](https://github.com/aflgo/aflgo/files/3310344/Installation_clang_4.docx)

**Comment by strongcourage** [comment]
Please see this blog: http://strongcourage.github.io/2019/06/20/aflgo.html
Build script: https://github.com/strongcourage/aflgo/blob/master/scripts/build/aflgo-build.sh
Thanks.

**Comment by Fayozbek** [comment]
> Hi. Thanks for your interest in our work. Please try to follow the installation steps in the attached file to install Clang/LLVM 4.0 and LLVM-Gold. It could resolve the issue.
> [Installation_clang_4.docx](https://github.com/aflgo/aflgo/files/3310344/Installation_clang_4.docx)

thank you for your super fast reply.
I am following "Installation_clang_4.docx" when I run `~/build-llvm/llvm$ ninja` in one-hour building process reach to 377 `[377/2141] Build CXX object .......` and then those number did not increase from 377 and Ubuntu stopped to work. I tried several times but OS stopped. 
Computer properties:
Intel(R) Core(TM) i5-6400 CPU 2.70 GHz 
Ram: 8 GB
x64

**Comment by Fayozbek** [comment]
Actually today I tried again to build ninja but... 
`bek@ubuntu:~/build-llvm/llvm$ ninja
[196/2141] Building CXX object lib/Tra.../LLVMVectorize.dir/LoopVectorize.cpp.o
FAILED: /usr/bin/c++   -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Transforms/Vectorize -I/home/bek/llvm-4.0.0.src/lib/Transforms/Vectorize -Iinclude -I/home/bek/llvm-4.0.0.src/include -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Werror=date-time -std=c++11 -ffunction-sections -fdata-sections -O3 -DNDEBUG    -fno-exceptions -fno-rtti -MMD -MT lib/Transforms/Vectorize/CMakeFiles/LLVMVectorize.dir/LoopVectorize.cpp.o -MF lib/Transforms/Vectorize/CMakeFiles/LLVMVectorize.dir/LoopVectorize.cpp.o.d -o lib/Transforms/Vectorize/CMakeFiles/LLVMVectorize.dir/LoopVectorize.cpp.o -c /home/bek/llvm-4.0.0.src/lib/Transforms/Vectorize/LoopVectorize.cpp
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[196/2141] Building CXX object lib/Tra.../LLVMVectorize.dir/SLPVectorizer.cpp.o
ninja: build stopped: subcommand failed.
`
