### ISSUE TITLE
libxml2 git repo address has changed

### ISSUE THREAD

**Issue by hexcoder-** [aflgo/aflgo#44]
In [README.md](https://github.com/aflgo/aflgo#how-to-instrument-a-binary-with-aflgo), 

> 4. Download subject (e.g., libxml2)

the git repo address has changed. It is now
[https://gitlab.gnome.org/GNOME/libxml2](https://gitlab.gnome.org/GNOME/libxml2).

**Comment by strongcourage** [comment]
Thanks. Fixed in 046293c.
