### ISSUE TITLE
About Simulated Annealing

### ISSUE THREAD

**Issue by LingXinL** [aflgo/aflgo#45]
Hello:
  I want to know the position of the Simulated Annealing algorithm in the code.
                                          thank you!

**Comment by strongcourage** [comment]
Hi @LingXinL,
Please see: https://github.com/aflgo/aflgo/blob/master/afl-fuzz.c#L4785-L4838

**Comment by LingXinL** [comment]
Ok，thank you

**Comment by LingXinL** [comment]
> 
> 
> Hi @LingXinL,
> Please see: https://github.com/aflgo/aflgo/blob/master/afl-fuzz.c#L4785-L4838

Ok，thank you
