### ISSUE TITLE
Please rewrite and test aflgo-build.sh

### ISSUE THREAD

**Issue by zjuchenyuan** [aflgo/aflgo#48]
https://github.com/aflgo/aflgo/blob/0f45722/scripts/build/aflgo-build.sh

## `set -e` can be added

Exit immediately if a command exits with a non-zero status.

## It's suggested to add `apt install sudo wget` for Docker building

Do not assume `sudo`, `curl` and `wget` are present by default

## Why do you clone clang from `chromium_tools`?

It seems `~/build/chromium_tools` is not used afterwards

## Please use correct command to decompress xz files

`tar xvzf` is for `tar.gz` files, not for `tar.xz`

`tar xf llvm-4.0.0.src.tar.xz` is enough here.

## Please change directory to `~/build` before decompress 

This version of script will download xz files to `~/build/chromium_tools`, not `~/build`

## Please change directory after `ninja install`

Or, you can change `mkdir -p build-llvm/msan; cd build-llvm/msan` to `mkdir -p ~/build/build-llvm/msan; cd ~/build/build-llvm/msan`

## About python version

Why do you install both python2 and python3? Do AFL-Go require both?

--------

Besides, please add `apt install -y pkg-config gawk` to `scripts/fuzz/libxml2-ef709ce2.sh`

**Comment by thuanpv** [comment]
Thanks for reporting the issue. I have fixed it.
