### ISSUE TITLE
llvm version: README say 4.0.1, while aflgo-build.sh use 4.0.0.

### ISSUE THREAD

**Issue by zjuchenyuan** [aflgo/aflgo#51]
I'm not familiar with llvm, can anybody tell me which llvm version should I use?

I can build aflgo with clang 4.0.0, do I need to change to higher or latest llvm version for better performance or something else?

Please make README and the building script consistent.

**Comment by zjuchenyuan** [comment]
Besides, aflgo-build.sh compile clang and llvm from source code, which takes long time, and makes DockerHub automated build time out.

I propose change to download and decompress pre-built binaries, like what Angora did: https://github.com/AngoraFuzzer/Angora/blob/master/build/install_llvm.sh

**Comment by strongcourage** [comment]
I use llvm version 4.0.0. AFLGo is currently "sensitive" with the clang version. We also plan to use the latest verion of llvm 8.

Please let me know if you can use pre-built binaries of llvm and clang to run AFLGo. We will update the building script. Thanks.

**Comment by zjuchenyuan** [comment]
It seems not that easy to skip compiling LLVM, since the pre-built binaries does not include LLVM-Gold plugin. (Besides, llvm.org does not provide version 4.0.1 pre-built binaries for ubuntu, wierd...)

I will keep trying for easier using AFL-Go.

**Comment by strongcourage** [comment]
Thanks @zjuchenyuan for your tries. I think we have tried some cases, but got a conclusion to use oss-fuzz's building script. Also, if we use the newest version of clang and llvm, we may need to update llvm-mode.
