### ISSUE TITLE
Problems about Ftargets.txt and Generate Distance.

### ISSUE THREAD

**Issue by Kiwi071211** [aflgo/aflgo#52]
Hi, I have some problems about Ftargets.txt and Generate Distance when fuzzing LAVA-M benchamrk(base64).
1. How to create Ftargets.txt?
2. Is Ftargets.txt is necessary?
3. When I run step 7($AFLGO/scripts/genDistance.sh $SUBJECT $TMP_DIR xmllint) with LAVA-M benchamrk,  it said "No targets avaliable" and "Problem in step 2 of generating !", does it relative to Ftargets.txt? Or what should I do if not?
 I am waiting for your anwsers, thx!

**Comment by thuanpv** [comment]
Hi,

Ftargets should be created automatically by AFLGo based on the BBtargets.txt file (See Step 5 in Readme.md to learn how to create BBtargets.txt). Ftargets.txt is needed for AFLGo to calculate the distances.

How did you prepare BBtargets.txt? 

If you could provide all the detailed steps you followed to work with LAVA-M benchmark, it would be much easier for me to give you more suggestions.

**Comment by mboehme** [comment]
Closed as inactive.
