### ISSUE TITLE
bug in building llvm_mode

### ISSUE THREAD

**Issue by MRLEE123456** [aflgo/aflgo#57]
clang++ `llvm-config --cxxflags` -Wl,-znodelete -fno-rtti -fpic -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DVERSION=\"2.52b\" -Wno-variadic-macros -shared afl-llvm-pass.so.cc -o ../afl-llvm-pass.so `llvm-config --ldflags` 
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean
      '-Wno-uninitialized'? [-Wunknown-warning-option]
afl-llvm-pass.so.cc:374:24: error: no matching constructor for initialization of
      'llvm::raw_fd_ostream'
        raw_fd_ostream cfgFile(cfgFileName, EC,true);
                       ^       ~~~~~~~~~~~~~~~~~~~~
/usr/local/include/llvm/Support/raw_ostream.h:395:3: note: candidate constructor
      not viable: no known conversion from 'bool' to 'sys::fs::OpenFlags' for
      3rd argument
  raw_fd_ostream(StringRef Filename, std::error_code &EC,
  ^
/usr/local/include/llvm/Support/raw_ostream.h:400:3: note: candidate constructor
      not viable: no known conversion from 'std::string' (aka
      'basic_string<char>') to 'int' for 1st argument
  raw_fd_ostream(int fd, bool shouldClose, bool unbuffered=false);
  ^
/usr/local/include/llvm/Support/raw_ostream.h:357:7: note: candidate constructor
      (the implicit copy constructor) not viable: requires 1 argument, but 3
      were provided
class raw_fd_ostream : public raw_pwrite_stream {
      ^
1 warning and 1 error generated.
Makefile:84: recipe for target '../afl-llvm-pass.so' failed
make: *** [../afl-llvm-pass.so] Error 1

**Comment by mboehme** [comment]
Maybe related to PR #55. Can you checkout c2888eb4 and build?

**Comment by adrianherrera** [comment]
Hi @MRLEE123456,

What version of clang are you using? As @mboehme suggested, I would pull down the latest version: the `raw_fd_ostream` constructor has changed (https://github.com/aflgo/aflgo/blob/master/llvm_mode/afl-llvm-pass.so.cc#L375)

**Comment by OskarBo** [comment]
I got the same error like @MRLEE123456  with the newest building script of AFLGo. After checking out c2888eb of AFLGo the build in LLVM mode works again.

**Comment by adrianherrera** [comment]
Cool, I think I'll close this then.
