### ISSUE TITLE
Error in building binutils

### ISSUE THREAD

**Issue by OskarBo** [aflgo/aflgo#59]
My error description is very similar to #37 which has been closed due to inactivity.

When building binutils with Clang + Gold I get the following error:

**/usr/bin/ld.gold: error: arlex.o: multiple definition of 'yylex'
/usr/bin/ld.gold: ar.o: previous definition here**

**Additional Information:**
OS: Ubuntu 18.04.3
Clang version: I tried 4.0.0, 4.0.1, and 6.0.0 (all result in same error)
Binutils version: I tried 2.33.1 and 2.29.1 (all result in sam error)
Configure Flags: --disable-werror --disable-shared --disable-ld (all result in sam error)
Gold Linker: I tried version  1.15 and 1.16

I am able to build binutils with clang, when skipping the gold arguments.

Is ther anything else I could try?

Edit: Added gold linker version

**Comment by strongcourage** [comment]
Hi, did you try to compile Binutils using the following configuration: 
~~~
CFLAGS="-DFORTIFY_SOURCE=2 -fstack-protector-all -fno-omit-frame-pointer -g -Wno-error $ADDITIONAL" LDFLAGS="-ldl -lutil" ../configure --disable-shared --disable-gdb --disable-libdecnumber --disable-readline --disable-sim --disable-ld
~~~

**Comment by OskarBo** [comment]
Using these flags and arguments Clang 4.0.0 results in the same error for Binutils 2.33.1 and 2.29.1

**Comment by OskarBo** [comment]
I understand that this is a very specific problem which is probably system oder library related. I would be very grateful if somebody could share his/her system specs together with the versions of all tools used in the toolchain. Then I could try to recreate the environment in order to finally get AFLGo running with binutils. 

I am kind of in hurry because I need a running AFLGo (with binutils) for my Master thesis. Thanks in advance! :)

**Comment by strongcourage** [comment]
I'd suggest you to install Ubuntu 16.04, then use our script to build Clang and AFLGo. I used this configuration and could fuzz Binutils without issues. Best.

**Comment by OskarBo** [comment]
Thank you! I will try this and then report back.

**Comment by OskarBo** [comment]
Apparently it works on a clean Ubuntu 16.04. I used the build and the fuzz script of AFLGo and everything is working fine.

Thanks for your help!

**Comment by bjchan9an** [comment]
I found that use ``make -j`` could sometimes solve this problem. Although this is not a fundamental solution (e.g., switch to ubuntu 16.04), this solution is useful your are in a hurry.
