### ISSUE TITLE
Readable file for crashes fuzzed input

### ISSUE THREAD

**Issue by clothildejeangoudoux** [aflgo/aflgo#61]
Hi,

I am using AFLGo on numerical code, with floating-point inputs. When running the program, AFLGo finds crashes for some of the fuzzed inputs.

I want to be able to extract the input for which the code crashed. I give to AFLGo a seed corpus of 25 values, all of them scanned into double variables.

My issue is that the files in build/out/crashes look like this:
·621.0 6955 .8165.9469.5861..4778.494
4.0
27.05 37 63.6 0.52.68 1 0 8
-1 1.636.7 0.38.1

My understanding is that AFLGo prints bytes into the out/crashes file, which could be one of the reason why it is not readable as is. The problem is that file contains 88 bytes, which is not enough to represent 25 double values.

Is there a simple way for me to get the values generated by AFLGo in a readable format?

**Comment by strongcourage** [comment]
Hi,

For your question, I think no because it is more likely that fuzzed inputs are invalid formats. You can run afl-tmin to minimize the crashing input. Also, you can debug the tested program given the crashing input to detect the vulnerable code. 

Best.
