### ISSUE TITLE
problems on AFLGo Building Script

### ISSUE THREAD

**Issue by Kiwi071211** [aflgo/aflgo#64]
when ninja running, there are some errors:
    1. ninja: build stopped : subcommand failed;
    2. c++ : internal compiler error: killed(program cc1plus)
what should I do ?
THX

**Comment by strongcourage** [comment]
Hi. Can you please show your compilation errors?

**Comment by thuanpv** [comment]
And please tell us your environment information (e.g., OS) + steps you have followed

**Comment by Kiwi071211** [comment]
OS: ubuntu18.4
steps：
# build clang & LLVM
LLVM_DEP_PACKAGES="build-essential make cmake ninja-build git subversion python2.7 binutils-gold binutils-dev curl wget"
sudo apt-get install -y $LLVM_DEP_PACKAGES

mkdir ~/build; cd ~/build
mkdir llvm_tools; cd llvm_tools

wget http://releases.llvm.org/4.0.0/llvm-4.0.0.src.tar.xz
wget http://releases.llvm.org/4.0.0/cfe-4.0.0.src.tar.xz
wget http://releases.llvm.org/4.0.0/compiler-rt-4.0.0.src.tar.xz
wget http://releases.llvm.org/4.0.0/libcxx-4.0.0.src.tar.xz
wget http://releases.llvm.org/4.0.0/libcxxabi-4.0.0.src.tar.xz
tar xf llvm-4.0.0.src.tar.xz
tar xf cfe-4.0.0.src.tar.xz
tar xf compiler-rt-4.0.0.src.tar.xz
tar xf libcxx-4.0.0.src.tar.xz
tar xf libcxxabi-4.0.0.src.tar.xz

mv cfe-4.0.0.src ~/build/llvm_tools/llvm-4.0.0.src/tools/clang
mv compiler-rt-4.0.0.src ~/build/llvm_tools/llvm-4.0.0.src/projects/compiler-rt
mv libcxx-4.0.0.src ~/build/llvm_tools/llvm-4.0.0.src/projects/libcxx
mv libcxxabi-4.0.0.src ~/build/llvm_tools/llvm-4.0.0.src/projects/libcxxabi
mkdir -p build-llvm/llvm; cd build-llvm/llvm

cmake -G "Ninja" \
      -DLIBCXX_ENABLE_SHARED=OFF -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
      -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86" \
      -DLLVM_BINUTILS_INCDIR=/usr/include ~/build/llvm_tools/llvm-4.0.0.src

ninja; sudo ninja install

**Comment by Kiwi071211** [comment]
> 
> 
> Hi. Can you please show your compilation errors?

g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,

ninja : build stopped : subcommand falied.

**Comment by strongcourage** [comment]
I think there is no problem in compiling AFLGo's source code since you have not compile successfully LLVM yet.
First, please make sure you have more 30Gb free space (if I remember correctly).
If not, by googling your errors, maybe you can [increase the RAM](https://github.com/tdlib/td/issues/334) used.

**Comment by Kiwi071211** [comment]
> 
> 
> I think there is no problem in compiling AFLGo's source code since you have not compile successfully LLVM yet.
> First, please make sure you have more 30Gb free space (if I remember correctly).
> If not, by googling your errors, maybe you can [increase the RAM](https://github.com/tdlib/td/issues/334) used.

This is much better than before !XD
But when 'ninja' running , there is an error again: 
       ~/build/llvm_tools/llvm-4.0.0.src/projects/libcxx/include/__locale:39:11:fatal error: xlocale.h: No such file or directory

**Comment by strongcourage** [comment]
By googling, I found a solution for Ubuntu 18.04 (https://github.com/carla-simulator/carla/issues/503):
~~~
ln -s /usr/include/locale.h /usr/include/xlocale.h
~~~
