### ISSUE TITLE
Can't compile LLVM-instrumentation pass

### ISSUE THREAD

**Issue by DocMorris96** [aflgo/aflgo#65]
Hello,
I'm trying to install AFLGo and followed the instructions on how to fuzz a binary with AFLGo. LLVM 4.0.0 is installed with cmake version 3.17.0 on Linux Mint 19.3 64-bit. I also tried it with LLVM 4.0.1 and got the same result. When trying to compile the code in aflgo/llvm_mode with "sudo make clean all" I get the following error message:

rm -f *.o *.so *~ a.out core core.[1-9][0-9]* test-instr .test-instr0 .test-instr1 
rm -f ../afl-clang-fast ../afl-llvm-pass.so ../afl-llvm-rt.o ../afl-llvm-rt-32.o ../afl-llvm-rt-64.o ../afl-clang-fast++
[*] Checking for working 'llvm-config'...
[*] Checking for working 'clang'...
[*] Checking for '../afl-showmap'...
[+] All set and ready to build.
clang -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  afl-clang-fast.c -o ../afl-clang-fast 
ln -sf afl-clang-fast ../afl-clang-fast++
clang++ `llvm-config --cxxflags` -Wl,-znodelete -fno-rtti -fpic -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DVERSION=\"2.52b\" -Wno-variadic-macros -shared afl-llvm-pass.so.cc -o ../afl-llvm-pass.so `llvm-config --ldflags` 
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
afl-llvm-pass.so.cc:397:24: error: no matching constructor for initialization of 'llvm::raw_fd_ostream'
        raw_fd_ostream cfgFile(cfgFileName, EC);
                       ^       ~~~~~~~~~~~~~~~
/usr/local/include/llvm/Support/raw_ostream.h:400:3: note: candidate constructor not viable: no known conversion from 'std::string'
      (aka 'basic_string<char>') to 'int' for 1st argument
  raw_fd_ostream(int fd, bool shouldClose, bool unbuffered=false);
  ^
/usr/local/include/llvm/Support/raw_ostream.h:357:7: note: candidate constructor (the implicit copy constructor) not viable:
      requires 1 argument, but 2 were provided
class raw_fd_ostream : public raw_pwrite_stream {
      ^
/usr/local/include/llvm/Support/raw_ostream.h:395:3: note: candidate constructor not viable: requires 3 arguments, but 2 were
      provided
  raw_fd_ostream(StringRef Filename, std::error_code &EC,
  ^
1 warning and 1 error generated.
Makefile:84: recipe for target '../afl-llvm-pass.so' failed

**Comment by gytsen** [comment]
#67 should have fixed this issue, could you pull the latest master and try again?

**Comment by DocMorris96** [comment]
Hey gytsen, I just pulled the latest master and launched it. Now I get the following error message: 

rm -f *.o *.so *~ a.out core core.[1-9][0-9]* test-instr .test-instr0 .test-instr1 
rm -f ../afl-clang-fast ../afl-llvm-pass.so ../afl-llvm-rt.o ../afl-llvm-rt-32.o ../afl-llvm-rt-64.o ../afl-clang-fast++
[*] Checking for working 'llvm-config'...
[*] Checking for working 'clang'...
[*] Checking for '../afl-showmap'...
[+] All set and ready to build.
clang -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  afl-clang-fast.c -o ../afl-clang-fast 
ln -sf afl-clang-fast ../afl-clang-fast++
clang++ `llvm-config --cxxflags` -Wl,-znodelete -fno-rtti -fpic -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DVERSION=\"2.52b\" -Wno-variadic-macros -shared afl-llvm-pass.so.cc -o ../afl-llvm-pass.so `llvm-config --ldflags` 
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
clang -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  -fPIC -c afl-llvm-rt.o.c -o ../afl-llvm-rt.o
[*] Building 32-bit variant of the runtime (-m32)... failed (that's fine)
[*] Building 64-bit variant of the runtime (-m64)... success!
[*] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN AFL_INST_RATIO; AFL_QUIET=1 AFL_PATH=. AFL_CC=clang ../afl-clang-fast -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  ../test-instr.c -o test-instr 
error: unable to load plugin '../afl-llvm-pass.so': '../afl-llvm-pass.so: undefined symbol: _ZTVN4llvm17GetElementPtrInstE'
Makefile:98: recipe for target 'test_build' failed
make: *** [test_build] Error 1
