### ISSUE TITLE
BBtargets Content

### ISSUE THREAD

**Issue by oneCoderMan** [aflgo/aflgo#68]
Hello, may I ask you a question? What are the requirements for the content BBtargets  ? Can I input it by myself (I can specify a line by myself)? Or do I have to get it from the diff file by libxml2 as the step 5? thanks!

**Comment by thuanpv** [comment]
Sure, you can write the BBtargets file manually. The file contains multiple lines, each line has the following structure

file_name,target_line_number

For example

main.c,1234
