### ISSUE TITLE
test crashes for libxml2

### ISSUE THREAD

**Issue by peach-byte** [aflgo/aflgo#70]
hello,
I have fuzzed `libxml2` using your script [here](https://github.com/strongcourage/aflgo/blob/master/scripts/fuzz/libxml2-ef709ce2.sh).
after one hour I stopped it and now I want to test its crashes.

I want to run `xmllint` for each crash file and see the output crash.
how can I run this in gdb?
`xmlint` gets a lot of argument and I'm confused about them.

Thank you.

**Comment by thuanpv** [comment]
Suppose that you have a crash-triggering input fname. You can follow the steps below to reproduce the crash with gdb

gdb ./xmllint 
r --valid --recover fname

I hope it helps.

Thuan
