### ISSUE TITLE
How to build ffmpeg with aflgo?

### ISSUE THREAD

**Issue by bjchan9an** [aflgo/aflgo#71]
I am worried about how to build ffmpeg using aflgo, I tried to use:
```
cc="$CC" cxx="$CXX" CFLAGS="-flto -fuse-ld=gold -g3 -Wno-error -Wl,-plugin-opt=save-temps" CXXFLAGS="-flto -fuse-ld=gold -g3 -Wno-error -Wl,-plugin-opt=save-temps" ../configure --disable-shared --prefix=`pwd`
```
but failed.

The error info is
```
afl-clang-fast is unable to create an executable file.
If /home/k/afl_double_detect/afl-clang-fast is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
```

Or if I remove the option ``-flto``， I can build ffmpeg successfully, but I can't get the bitcode file. Can you help me?

**Comment by strongcourage** [comment]
Hi,
Can you try other compilation parameters, for example using --extra-cflags="..." instead of CFLAGS="...", as shown in [this tutorial](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#FFmpeg)? You can also take a look on the similar issue #69. 
Best.

**Comment by thuanpv** [comment]
Hi @bjchan9an,

As @strongcourage said, you can try other flags. I normally use --host-cflags and --host-ldflags.

I hope it helps.

Thuan

**Comment by bjchan9an** [comment]
Thank you, I will try it.

**Comment by Splines** [comment]
@bjchan9an Did you manage to build FFmpeg using AFLGo? If so, it'd be great if you could share your script with us.
