### ISSUE TITLE
-m32 is not supported by your compiler

### ISSUE THREAD

**Issue by wehann** [aflgo/aflgo#73]
Hello,
these days I am trying to run some scripts in "aflgo/scripts/fuzz/", but when I was building the projects (for example, line 9 in LMS.sh, `LINK=STATIC CFLAGS="$ADDITIONAL" CXXFLAGS="$ADDITIONAL" ./build.sh`), I was always told that "-m32 is not supported by your compiler". The last instruction run in building process and the outputs are:

```
[44/52] Linking C executable challenges/LMS/LMS_patched
FAILED: : && /home/user/Desktop/tests/LMS/../../aflgo/afl-clang-fast  -g -distance=/home/user/Desktop/tests/LMS/LMS/obj-aflgo/temp/distance.cfg.txt  -lpthread -m32 -static -Wl,--allow-multiple-definition -z execstack -z norelro challenges/LMS/CMakeFiles/LMS_patched.dir/lib/libc.c.o challenges/LMS/CMakeFiles/LMS_patched.dir/src/service.c.o  -o challenges/LMS/LMS_patched  include/libcgc.a include/tiny-AES128-C/libtiny-AES128-C.a && :

[-] PROGRAM ABORT : -m32 is not supported by your compiler
         Location : edit_params(), afl-clang-fast.c:297

[44/52] Building C object challenges/LMS/CMakeFiles/LMS.dir/lib/libc.c.o
ninja: build stopped: subcommand failed.
/home/user/Desktop/tests/LMS/LMS/build/challenges/LMS

```

For the instruction in second line, I noticed that -m32 mode is used by aflgo/afl-clang-fast, while something went wrong. Further more, I installed afl-clang by using apt-get, but -m32 is also not supported by afl-clang-fast here. 

Then I tried another script, KTY_Pretty_Printer, but the building process got stuck in -m32 instruction again. However, I can finish the whole process in README, I think that means my AFLGO can run smoothly. 

So I wonder how I can accomplish the building process? Thank you!

**Comment by strongcourage** [comment]
Hi @wehann,

I did not face your issue. Please make sure that you installed the following packages on Linux (see [README.md of CGC](https://github.com/trailofbits/cb-multios/blob/master/README.md)):
~~~
libc6-dev libc6-dev-i386 gcc-multilib g++-multilib clang cmake
~~~

Best. MD

**Comment by strongcourage** [comment]
Feel free to reopen if you have any questions. Thanks.
