### ISSUE TITLE
cooling_schedule

### ISSUE THREAD

**Issue by jintong0930** [aflgo/aflgo#78]
Hello, I want to ask where the four scheduling methods of T are obtained in the cooling schedule, that is SAN_EXP、SAN_LOG、SAN_QUAD、SAN_LIN.

**Comment by strongcourage** [comment]
Hi @jintong0930,

Here you are: https://github.com/aflgo/aflgo/blob/master/afl-fuzz.c#L4819-L4866.

Best. MD

**Comment by jintong0930** [comment]
I know that you have these four parameters in your source code, but how do you get these four formulas? Are they self-contained in the cooling schedule of simulated annealing algorithm

**Comment by strongcourage** [comment]
If you want to learn more about those formulars, please read Section 4.1 Power Schedules of AFLFast (https://mboehme.github.io/paper/CCS16.pdf).

**Comment by jintong0930** [comment]
That is to say, these four formulas were designed by your team, right

**Comment by strongcourage** [comment]
Yes, it's true.

**Comment by jintong0930** [comment]
Ok，thank you！

**Comment by jintong0930** [comment]
Hello,  I want to ask where the four scheduling methods of T are obtained in the cooling schedule, where can I find SAN_LOG, in Section 4.1 Power Schedules of AFLFast, there no find LOG.

**Comment by jintong0930** [comment]
I only can find EXP, QUAD, LIN, but no LOG in AFLFast.
