### ISSUE TITLE
Incorrect computation of normalized distance

### ISSUE THREAD

**Issue by bjchan9an** [aflgo/aflgo#79]
We found that the normalized distance could be computed incorrectly.  As shown in [afl-fuzz.c:4853](https://github.com/aflgo/aflgo/blob/master/afl-fuzz.c#L4853), when ``max_distance == min_distance``, the normalized distance is equal to the distance of the testcase. Thus, the normalized distance could be larger than 1.0, which leads to a quite small power factor.

**Comment by mboehme** [comment]
Thanks @bjchan9an! Good catch. Can you submit a PR with a bug fix?
