### ISSUE TITLE
Suggest to modify install script

### ISSUE THREAD

**Issue by kdsjZh** [aflgo/aflgo#82]
Recently i found a error like issue #42 ，the reason why error "cat: ..../AFLGO/temp/distance.callgraph.txt: No such file or directory" happen is not the file doesn't  exist, but networkx version conflict with python!!!
We all use the ubuntu 16.04 and use command apt-get install python3 ..., we install python 3.5, and networkx's current version(2.5) requires python>=3.6 so when using "import networkx as nx" , the error occurs.
Now I use networkx 2.1 and it works well. I'm now wondering if you can method this problem in readme or fix the install script?

**Comment by mboehme** [comment]
Can you submit a PR to modify the install script?

**Comment by mboehme** [comment]
Closing this. Feel free to reopen or submit a PR.
