### ISSUE TITLE
fuzzer warning

### ISSUE THREAD

**Issue by nntzuekai** [aflgo/aflgo#88]
Hi,

When the fuzzer attempts to have dry runs, it gives some warnings like this.

```
len = 734, map size = 422, exec speed = 2000 us
[!] WARNING: No new instrumentation output, test case may be useless.

[!] WARNING: Some test cases look useless. Consider using a smaller set.
```

Is this normal behaviour, or something wrong with my configuration?

Thanks,
Jerry

**Comment by strongcourage** [comment]
Yes, it is totally fine :)
