### ISSUE TITLE
What is the role that  LLVMgold plays?

### ISSUE THREAD

**Issue by xiaosatianyu** [aflgo/aflgo#9]
Hi!
As the instruction says, we should install LLVMgold first before running aflgo.
Why should do this and What is the role  LLVMgold plays in this process?
Thank you very much!

**Comment by aflgo** [comment]
The Gold plugin allows us to specify a parameter such that intermediate *.bc (bitcode) files are produced, as well, during compilation. The bitcode file for the main binary is being used to extract the call graph. The call graph (CG) and the control-flow graphs (CFGs) are then used to compute the distance values for each basic block.

The Gold plugin would not be necessary if we integrated everything into a single LLVM pass and computed the distance values on the internal representation of CG and CFGs inside the LLVM pass. For us, there was just not enough time to do that.

However, if there is a pull request, where everything is integrated into a single pass, then we would definitely be happy to review and integrate!
