### ISSUE TITLE
Linker command fail with afl-clang

### ISSUE THREAD

**Issue by blbi** [aflgo/aflgo#90]
Hi, 
I tried to run the fuzzer with mupdf 1.9.
However I got this error at the compiling step.
```
$ make
....
aflgo-compiler (yeah!) 2.52b
build/release/fontdump.o: file not recognized: File format not recognized
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:166: recipe for target 'build/release/fontdump' failed
make: *** [build/release/fontdump] Error 1
```

It is not only about the fontdump.o, all object file have same error, and any binaries are not generated in mupdf.
I've got no error with both gcc and afl-gcc.

Is there any problem in compiling mupdf with aflgo?

**Comment by mboehme** [comment]
Hi Blbi, Can you try building with vanilla AFL (or clang)? If the error persists, you probably need to fix it there first.

**Comment by blbi** [comment]
Yes, I have successfully built it with clang as follows.
```
$ make clean
$ export CC=clang
$ export CXX=clang++
$ make
```
There are no error messages and successfully generates the binary but afl-clang-fast still gives the error.😢

**Comment by mboehme** [comment]
In this case, it appears the problem is with LLVM. We have recently upgraded to LLVM 11.0. Maybe it works with this version?
Closing for now. Feel free to reopen.
