### ISSUE TITLE
Why to disable the default "-O3" option of afl-clang-fast

### ISSUE THREAD

**Issue by bjchan9an** [aflgo/aflgo#93]
Hello, thank you for your awesome work AFLGO. We noticed that you disable the default "-O3" optimization option of AFL in the afl-clang-fast.c. What is the reason? Could the "-O3" option affect the debug information obtaining in the LLVM pass?

**Comment by mboehme** [comment]
The reason could be that some important information within the CG and CFGs could be lost after optimization. Could you check whether it works for you after re-enabling it?

@strongcourage This was changed in https://github.com/aflgo/aflgo/commit/77c19af9d72f3b5bcb4eca0f19f6a47ce715cbee. Do you remember the reason?

**Comment by strongcourage** [comment]
Hi there, Exactly, this option was used to avoid optimization that may affect the distance values.
