### ISSUE TITLE
Are there any specific directories for the inputs that execute the target

### ISSUE THREAD

**Issue by quan-li-co** [aflgo/aflgo#94]
Hello~

I got some confusion when I was using AFL-go.

The question is that if AFL-go finds a mutated input that executes the targets, where to save this input? Are those special inputs saved into the queue folder and keep mutation? Based on my understanding, when AFL-go finds one input (through mutation) that executes the targets, in common sense, it should save those inputs into some specific location (like if the input crashes the program, it will be saved into the crash folder.). Since I think the goal of directed fuzzing is to find some inputs that execute targets. But in AFL-go, I just saw the mutated inputs are saved into the queue folder.  Is there any specific directory for those inputs that execute the target? If there is no specific directory, how do we know that if the input executes the target?

Thanks a lot for your answers.

**Comment by mboehme** [comment]
No, those inputs are not treated as special cases and stored separately. You could insert an `abort` statement at your target locations to induce a crash.

**Comment by mboehme** [comment]
Closing this issue as answered. Feel free to re-open if it didn't answer your question.
