### ISSUE TITLE
Recording the trace of specified seed

### ISSUE THREAD

**Issue by FrankWuwuwu** [aflgo/aflgo#98]
Hi,

Excellent project. I see that basic block level pins is inserted during compile. Suppose I have a specified input that may lead to a crush. Is there any way to get the basic block level execution trace of the specified seed through AFLGo?

**Comment by strongcourage** [comment]
Hi @FrankWuwuwu,

You may take a look at "AFLGO_PROFILER_FILE" [here](https://github.com/aflgo/aflgo/blob/master/llvm_mode/afl-llvm-rt.o.c#L452-L480). Note that it has overhead and you should not enable it during fuzzing.
Best.

**Comment by FrankWuwuwu** [comment]
Thanks for reply! I'm kind of not sure how to use it. I want to print all BBname when executing a specific seed. So, I can got a BBname trace after the execution.

**Comment by FrankWuwuwu** [comment]
@strongcourage

**Comment by strongcourage** [comment]
@FrankWuwuwu If you enable AFLGO_PROFILER_FILE, you will get a trace of covered basic blocks ID. Please see the code here https://github.com/aflgo/aflgo/blob/master/llvm_mode/afl-llvm-rt.o.c#L452-L479.
